[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Peter Simonsson <peter@simonsson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
